### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rockindash**
Clorde added to the list.

Do you consent to having your app icon used in promotional materials? Yes please

### CODE REVIEW

**Review by mattcorey — COMMENTED** [review]
You must have used a formatter that changed the entire file, so I can't visually compare your changes.  I will create a new PR with just Clorde, and submit it to you for review

**Comment by mattcorey** [comment]
Can you please review this PR?  It includes only the addition of Clorde, without the formatting:  https://github.com/mattcorey/indie-dev-sales/pull/77

**Comment by Rockindash** [comment]
Thanks for the effort. I really appreciate it.
The information is correct, checked the links as well.

**Comment by mattcorey** [comment]
Cool!  Merged the other PR, and closing this one.

**Pull request closed without merging**
